version: "3.9"

services:
  ruby: &base
    image: ruby:3.2.0-slim
    volumes:
      - ./quiz:/quiz
    working_dir: /quiz

  java:
    <<: *base
    image: eclipse-temurin:17.0.5_8-jdk

  python:
    <<: *base
    image: python:3.12.0a4-slim-bullseye

  c:
    <<: *base
    image: gcc:12.2.0

  go:
    <<: *base
    image: golang:1.19.5-bullseye

  js:
    <<: *base
    image: node:19.4.0-slim

  typescript:
    <<: *base
    image: denoland/deno:1.29.2

  rust:
    <<: *base
    image: rust:1.66.1-slim-buster

  erlang:
    <<: *base
    image: erlang:25.2.0.0-slim
