#!/bin/bash

# lq outputs last question directory name
# ex) cd `./lq rb` # -> move to last directory that contains rb file

dir=$(dirname $(realpath $0))
echo `find $dir | grep $1 | tail -n1 | xargs dirname`
